/**
 * 数据接口 
 * generated by if-sync @徐凯-鬼道
 *
 * @author 黄甲
 * @version 1.0.0
 * @date 10/12/13
 */

/**
 * 兼容node和browser环境
 */
if (typeof exports === "undefined") {
    exports = {};
}

exports.config = {
    "name": "营销效果查询",
    "desc": ""
};


exports.request = {
    // 推广 名称 状态
    planId:32,
    spreadState : "进行中", 

    // 推广开始时间
    gmtGenerateStart : "", 

    // 推广结束时间
    gmtGenerateEnd : "",   

    // radios 数据筛选指标
    effectIndicator : 14,

    // radios 组选指标 
    groupId : 2121
}

exports.response = { 

    // select 推广名称
    spreadNames : [{"value":"", "text":"请选择", "selected": "selected"}, {"value":1, "text":1}, {"value":2, "text":2}, {"value":3, "text":3}], 

    // select 推广名称 默认选中数据
    spreadId:32,

    // 推广状态                                                                                                                 
    spreadState : "进行中",                                                        

    // 推广开始时间
    gmtGenerateStart : "", 

    // 推广结束时间
    gmtGenerateEnd : "",   

    // radios 数据筛选指标
    indicators : [{"value":1, "text":"曝光量", "checked": "checked"}, {"value":2, "text":2}, {"value":3, "text":3}], 

    // radios 组选指标 
    groups : [{"value":1, "text":1, "checked": "checked"}, {"value":2, "text":2}, {"value":3, "text":3}],  

    // 梯形图数据
    keystoneData : [{"name":"定投用户数", "num":14544, "percentage":""}, {"name":"点击用户数", "num":45544, "percentage":"点击率15%"}, {"name":"点击用户数2", "num":45544, "percentage":"点击率30%"}, {"name":"点击用户数3", "num":45544, "percentage":"点击率45%"}],
   
    // 曲线图数据
    "LineChartData" : {
        "ydata": [100,935,200,400,144,234,700, 400,480,200,700,144,1234,100],
        "xdata": [100,935,200,400,144,234,700, 400,480,200,700,144,1234,100]
    }, 
    
    // 饼图数据
    "piechartData" : {
        "data" : [{"data":30, "label":"30%","tip":"per"},{"data":30,"label":"30%","tip":"per"},{"data":40,"label":"40%","tip":"percent"}, {"data":49,"label":"49%","tip":"percent"}],
        "list" : [{"text":"34% 天猫首聚焦"},{"text":"25% 天猫首聚焦2"},{"text":"45% 天猫首聚焦3"},{"text":"13% 天猫首聚焦4"}]
    },    

    // 表格数据
    "tableData" : [{
        //日期
        "gmtGenerate":"2013-05-25", 

        //定投用户数
        "userNos":2156, 

        //曝光pv
        "pv":556, 

        //点击量
        "click":2121, 

        //点击用户数
        "clickUser":25544, 

        //点击率
        "clickRate":"48%", 

        //收藏量
        "collectSum":2141242,

        //加入购物车量
        "inCartSum":213212, 

        // 用户数
        "inCartUser":21212,

        //成交笔数
        "tickcount":232323,

        //成交用户数
        "dealUser":212121,  

        //客单价
        "avgPrice":5454545, 

        //总金额
        "turnover":2223266 
    }]
}

exports.responseError = {

}